// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: test.proto

package gen2

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Doc struct {
	DocId       uint32 `protobuf:"varint,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Position    string `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Company     string `protobuf:"bytes,3,opt,name=company,proto3" json:"company,omitempty"`
	City        string `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	SchoolLevel int32  `protobuf:"varint,5,opt,name=school_level,json=schoolLevel,proto3" json:"school_level,omitempty"`
	Vip         bool   `protobuf:"varint,6,opt,name=vip,proto3" json:"vip,omitempty"`
	Chat        bool   `protobuf:"varint,7,opt,name=chat,proto3" json:"chat,omitempty"`
	Active      int32  `protobuf:"varint,8,opt,name=active,proto3" json:"active,omitempty"`
	WorkAge     int32  `protobuf:"varint,9,opt,name=work_age,json=workAge,proto3" json:"work_age,omitempty"`
}

func (m *Doc) Reset()         { *m = Doc{} }
func (m *Doc) String() string { return proto.CompactTextString(m) }
func (*Doc) ProtoMessage()    {}
func (*Doc) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{3}
}
func (m *Doc) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Doc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Doc.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Doc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Doc.Merge(m, src)
}
func (m *Doc) XXX_Size() int {
	return m.Size()
}
func (m *Doc) XXX_DiscardUnknown() {
	xxx_messageInfo_Doc.DiscardUnknown(m)
}

var xxx_messageInfo_Doc proto.InternalMessageInfo

func (m *Doc) GetDocId() uint32 {
	if m != nil {
		return m.DocId
	}
	return 0
}

func (m *Doc) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func (m *Doc) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *Doc) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Doc) GetSchoolLevel() int32 {
	if m != nil {
		return m.SchoolLevel
	}
	return 0
}

func (m *Doc) GetVip() bool {
	if m != nil {
		return m.Vip
	}
	return false
}

func (m *Doc) GetChat() bool {
	if m != nil {
		return m.Chat
	}
	return false
}

func (m *Doc) GetActive() int32 {
	if m != nil {
		return m.Active
	}
	return 0
}

func (m *Doc) GetWorkAge() int32 {
	if m != nil {
		return m.WorkAge
	}
	return 0
}

func init() {
	proto.RegisterType((*Doc)(nil), "gen.Doc")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x52, 0xbd, 0x4e, 0xf3, 0x30,
	0x14, 0xad, 0x9b, 0xe6, 0xa7, 0xb7, 0xfd, 0x3e, 0x21, 0x4b, 0x20, 0xc3, 0x60, 0x42, 0xa6, 0x0c,
	0x10, 0x10, 0x3c, 0x01, 0x88, 0x05, 0x89, 0xa1, 0xca, 0xc8, 0x12, 0x05, 0xc7, 0x4a, 0x2d, 0x52,
	0x3b, 0x4a, 0xac, 0xa2, 0xbe, 0x05, 0x8f, 0xc5, 0xd8, 0x91, 0x11, 0x25, 0xe2, 0x3d, 0x90, 0x9d,
	0xc0, 0x43, 0xb0, 0x9d, 0x1f, 0xfb, 0xdc, 0x7b, 0xa4, 0x0b, 0xa0, 0x79, 0xab, 0x93, 0xba, 0x51,
	0x5a, 0x61, 0xa7, 0xe4, 0x32, 0xba, 0x00, 0xbf, 0xe6, 0x4d, 0xab, 0xe4, 0x15, 0xfe, 0x0f, 0x53,
	0x51, 0x10, 0x14, 0xa2, 0xd8, 0x4d, 0xa7, 0xa2, 0xc0, 0x18, 0x66, 0x32, 0xdf, 0x70, 0x32, 0x0d,
	0x51, 0x3c, 0x4f, 0x2d, 0x8e, 0xce, 0x01, 0xf2, 0xaa, 0xca, 0x86, 0x2f, 0x98, 0x82, 0xb3, 0xe2,
	0x0d, 0x41, 0xa1, 0x13, 0x2f, 0xae, 0x97, 0x49, 0xc9, 0x65, 0x32, 0x86, 0xa5, 0xc6, 0x88, 0xbe,
	0x10, 0x78, 0xab, 0xe1, 0xe9, 0x21, 0x78, 0x85, 0x62, 0xd9, 0x38, 0xe0, 0x5f, 0xea, 0x16, 0x8a,
	0x3d, 0x14, 0xf8, 0x04, 0x82, 0x5a, 0xb5, 0x42, 0x0b, 0x25, 0xc7, 0x39, 0xbf, 0x1c, 0x13, 0xf0,
	0x99, 0xda, 0xd4, 0xb9, 0xdc, 0x11, 0xc7, 0x5a, 0x3f, 0xd4, 0x6c, 0xc6, 0x84, 0xde, 0x91, 0xd9,
	0xb0, 0x99, 0xc1, 0xf8, 0x0c, 0x96, 0x2d, 0x5b, 0x2b, 0x55, 0x65, 0x15, 0xdf, 0xf2, 0x8a, 0xb8,
	0xb6, 0xc7, 0x62, 0xd0, 0x1e, 0x8d, 0x84, 0x0f, 0xc0, 0xd9, 0x8a, 0x9a, 0x78, 0x21, 0x8a, 0x83,
	0xd4, 0x40, 0x1b, 0xb4, 0xce, 0x35, 0xf1, 0xad, 0x64, 0x31, 0x3e, 0x02, 0x2f, 0x67, 0x5a, 0x6c,
	0x39, 0x09, 0x6c, 0xc4, 0xc8, 0xf0, 0x31, 0x04, 0xaf, 0xaa, 0x79, 0xc9, 0xf2, 0x92, 0x93, 0xb9,
	0x75, 0x7c, 0xc3, 0x6f, 0x4b, 0x1e, 0x75, 0x08, 0x9c, 0x7b, 0xc5, 0xfe, 0x74, 0xc9, 0xbb, 0xd3,
	0xf7, 0x8e, 0xa2, 0x7d, 0x47, 0xd1, 0x67, 0x47, 0xd1, 0x5b, 0x4f, 0x27, 0xfb, 0x9e, 0x4e, 0x3e,
	0x7a, 0x3a, 0x79, 0x72, 0x93, 0xcb, 0x92, 0xcb, 0x67, 0xcf, 0x9e, 0xd5, 0xcd, 0x77, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x9d, 0x84, 0x4c, 0x72, 0x64, 0x02, 0x00, 0x00,
}

func (m *Doc) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Doc) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Doc) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.WorkAge != 0 {
		i = encodeVarintTest(dAtA, i, uint64(m.WorkAge))
		i--
		dAtA[i] = 0x48
	}
	if m.Active != 0 {
		i = encodeVarintTest(dAtA, i, uint64(m.Active))
		i--
		dAtA[i] = 0x40
	}
	if m.Chat {
		i--
		if m.Chat {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.Vip {
		i--
		if m.Vip {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.SchoolLevel != 0 {
		i = encodeVarintTest(dAtA, i, uint64(m.SchoolLevel))
		i--
		dAtA[i] = 0x28
	}
	if len(m.City) > 0 {
		i -= len(m.City)
		copy(dAtA[i:], m.City)
		i = encodeVarintTest(dAtA, i, uint64(len(m.City)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Company) > 0 {
		i -= len(m.Company)
		copy(dAtA[i:], m.Company)
		i = encodeVarintTest(dAtA, i, uint64(len(m.Company)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Position) > 0 {
		i -= len(m.Position)
		copy(dAtA[i:], m.Position)
		i = encodeVarintTest(dAtA, i, uint64(len(m.Position)))
		i--
		dAtA[i] = 0x12
	}
	if m.DocId != 0 {
		i = encodeVarintTest(dAtA, i, uint64(m.DocId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTest(dAtA []byte, offset int, v uint64) int {
	offset -= sovTest(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}

func (m *Doc) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DocId != 0 {
		n += 1 + sovTest(uint64(m.DocId))
	}
	l = len(m.Position)
	if l > 0 {
		n += 1 + l + sovTest(uint64(l))
	}
	l = len(m.Company)
	if l > 0 {
		n += 1 + l + sovTest(uint64(l))
	}
	l = len(m.City)
	if l > 0 {
		n += 1 + l + sovTest(uint64(l))
	}
	if m.SchoolLevel != 0 {
		n += 1 + sovTest(uint64(m.SchoolLevel))
	}
	if m.Vip {
		n += 2
	}
	if m.Chat {
		n += 2
	}
	if m.Active != 0 {
		n += 1 + sovTest(uint64(m.Active))
	}
	if m.WorkAge != 0 {
		n += 1 + sovTest(uint64(m.WorkAge))
	}
	return n
}

func sovTest(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTest(x uint64) (n int) {
	return sovTest(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}


func (m *Doc) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTest
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Doc: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Doc: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DocId", wireType)
			}
			m.DocId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DocId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Position", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Position = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Company", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Company = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field City", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.City = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SchoolLevel", wireType)
			}
			m.SchoolLevel = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SchoolLevel |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vip", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Vip = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chat", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Chat = bool(v != 0)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Active", wireType)
			}
			m.Active = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Active |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WorkAge", wireType)
			}
			m.WorkAge = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WorkAge |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTest(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTest
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTest(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTest
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTest
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTest
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTest
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTest
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTest
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTest        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTest          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTest = fmt.Errorf("proto: unexpected end of group")
)
